//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAseguradora.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAdiccionesClientes
    {
        public int ID_ACliente_Ac { get; set; }
        public int ID_Adiccion_Ac { get; set; }
        public int ID_DPersona_Ac { get; set; }
    
        public virtual TblAddiciones TblAddiciones { get; set; }
        public virtual TblDetallePersona TblDetallePersona { get; set; }
    }
}
