//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAseguradora.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAddiciones
    {
        public TblAddiciones()
        {
            this.TblAdiccionesClientes = new HashSet<TblAdiccionesClientes>();
        }
    
        public int ID_Adiccion_Ad { get; set; }
        public string Nombre_Ad { get; set; }
        public string Codigo_Ad { get; set; }
    
        public virtual ICollection<TblAdiccionesClientes> TblAdiccionesClientes { get; set; }
    }
}
