//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAseguradora.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDetallePolizas
    {
        public TblDetallePolizas()
        {
            this.TblPolizas = new HashSet<TblPolizas>();
        }
    
        public int ID_DPoliza_Dpl { get; set; }
        public string Nombre_Dpl { get; set; }
        public string Descripción_Dpl { get; set; }
        public int Porcentaje_Dpl { get; set; }
    
        public virtual ICollection<TblPolizas> TblPolizas { get; set; }
    }
}
