//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAseguradora.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPolizas
    {
        public TblPolizas()
        {
            this.TblSeguros = new HashSet<TblSeguros>();
        }
    
        public int ID_Polizas_Pol { get; set; }
        public int ID_DPoliza_Pol { get; set; }
        public int ID_DPersona_Pol { get; set; }
        public decimal MontoAsegurado_Pol { get; set; }
        public int PorcentajeCobertura_Pol { get; set; }
        public int NumAdicciones_Pol { get; set; }
        public decimal MontoAdicciones_Pol { get; set; }
        public decimal PrimaAntesImp_Pol { get; set; }
        public decimal Impuestos_Pol { get; set; }
        public decimal PrimaFinal_Pol { get; set; }
        public System.DateTime Fecha_Pol { get; set; }
    
        public virtual TblDetallePersona TblDetallePersona { get; set; }
        public virtual TblDetallePolizas TblDetallePolizas { get; set; }
        public virtual ICollection<TblSeguros> TblSeguros { get; set; }
    }
}
