//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAseguradora.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSeguros
    {
        public int ID_Seguro_Se { get; set; }
        public int ID_Polizas_Se { get; set; }
        public int ID_Provincia_Se { get; set; }
        public int ID_DPersona_Se { get; set; }
    
        public virtual TblDetallePersona TblDetallePersona { get; set; }
        public virtual TblPolizas TblPolizas { get; set; }
        public virtual TblProvincia TblProvincia { get; set; }
    }
}
